### ISSUE TITLE
FirebaseApp is not initialized in this process

### ISSUE THREAD

**Issue by flutternoob** [nhandrew/uploadimages#1]
I get the following exception, when I run the code as per the tutorial:

<details>
<summary>
Logs
</summary>

```
E/flutter (  520): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(error, Default FirebaseApp is not initialized in this process com.example.flutter_firebase_storage. Make sure to call FirebaseApp.initializeApp(Context) first., null)
```
</details>

**Comment by nhandrew** [comment]
It looks like you may not have imported your google-services.json file as part of the firebase setup.  Double check the steps here https://firebase.google.com/docs/flutter/setup?authuser=0&platform=android

**Comment by flutternoob** [comment]
Thanks! That fixed the problem.
